services:
  server:
    build:
      context: .
    ports:
      - 8080:8080
    environment:
      # These environment variables automatically override application.properties
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/library_db
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=password123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres
    restart: always
    volumes:
      - db-data:/var/lib/postgresql
    environment:
      - POSTGRES_DB=library_db
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=password123
    ports:
      - "5432:5432" # Exposes to my machine so I can use DBeaver/Datagrip
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db-data:
