spring.application.name=library-backend

# H2 database
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=jdbc:postgresql://localhost:5432/library_db
spring.datasource.username=sa
spring.datasource.password=password123

# Auto create/update tables from entities
spring.jpa.hibernate.ddl-auto=update

# JWT Configuration
app.jwt.secret=
app.jwt.expiration=3600000
app.jwt.refresh-expiration=86400000